import type { WorkerInput } from "@/types/db";

// 氏名だけで外国人を新規登録するときの既定値（残りは後から詳細入力）
export function blankWorkerInput(name: string, organizationId: string | null = null): WorkerInput {
  return {
    name: name.trim(),
    kana: "",
    nationality: "",
    birth: null,
    residence_card_no: "",
    field: "",
    support: "支援開始前",
    status: "申請準備中",
    health_note: "",
    family_note: "",
    current_organization_id: organizationId,
    residence_status: "",
    residence_permit_date: null,
    residence_expiry_date: null,
    passport_no: "",
    passport_expiry_date: null,
    notion_link: "",
    residence_renewal_status: "",
    residence_renewal_todo: "",
    application_prep_kind: "",
    leaving_on: null,
    leaving_todo: "",
    leaving_kind: "",
    leaving_reason: "",
    leaving_org_name: "",
    leaving_org_address: "",
    gender: "",
    address: "",
    employment_start_on: null,
    assigned_office: "",
    residence_note: "",
    photo_path: null,
    messenger_link: "",
    specialty_grade: "",
    other_qualifications: "",
    note: "",
  };
}
